x=input("enter your name")
y=input("enter your college name")
z=input("enter your course name")
a=input("enter your date of birth")
b=input("enter your sslc marks")
print(x)
print(y)
print(z)
print(str(a))
print(str(b))