x=[10,20,30,40,20,10]
l=len(x)
print(str(l))
x.append(100)
print(str(x))
x.insert(25,34)
print(str(x))
x.pop()
print(str(x))
x.remove(40)
print(str(x))
y=x.index(20)
print("index of given number="+str(y))
z=x.count(20)
print("the given number is repeated "+str(z)+ " times")
a=x.clear()
print(str(a))